---
driver:
  name: vagrant
  provider: libvirt
  customize:
    uri: qemu+ssh://root@172.17.0.1/system
    #uri: qemu+ssh://root@ci.concerto.io/system
    username: root
    memory: 1024
    random_hostname: true
    cpus: 2

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      box: ptemmerman/ubuntu16.04-x64
  - name: ubuntu-14.04
    driver:
      box: ptemmerman/ubuntu14.04-x64

suites:
  - name: default
    run_list:
      - recipe[mysql-docker::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
